src/organdonate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^register/', include('register.urls', namespace='register')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

src/register/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.register_donor, name='create'),
    url(r'^(?P<id>[0-9a-z-]+)/donor-card/$', views.download_donor_card, name='pdf'),
    url(r'^(?P<id>[0-9a-z-]+)/$', views.donor_detail, name='detail'),
    #url(r'^thank-you/$', views.register_success, name='sucess')
]

src/register/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
import uuid

class Organ(models.Model):
    name             = models.CharField(max_length=50)
    description      = models.TextField()
    
    def __str__(self):
        return self.name

class Donor(models.Model):
    first_name       = models.CharField(max_length=50)
    last_name        = models.CharField(max_length=50)
    gender           = models.IntegerField()
    email            = models.EmailField(unique=True)
    date_of_birth    = models.DateField(auto_now_add=False, auto_now=False)
    contact_no       = models.PositiveIntegerField(max_length=10, unique=True, validators=[RegexValidator(regex='^\d{10}$', message='Length has to be 10', code='Invalid number')])
    emergeny_contact = models.PositiveIntegerField(max_length=10, unique=True, validators=[RegexValidator(regex='^\d{10}$', message='Length has to be 10', code='Invalid number')])
    street_add1      = models.CharField(max_length = 50)
    street_add2      = models.CharField(max_length = 50)
    city             = models.CharField(max_length = 50)
    state            = models.CharField(max_length = 50)
    postal_code      = models.PositiveIntegerField()
    id               = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    registered       = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated          = models.DateTimeField(auto_now_add=False, auto_now=True)
    organ            = models.ManyToManyField(Organ)
    
    def __str__(self):
        return self.first_name
    
    def get_absolute_url(self):
        return reverse('register:detail', kwargs={"id": self.id})

src/register/forms.py
from django import forms

from .models import Donor

class DonorForm(forms.ModelForm):
    class Meta:
        model = Donor
        fields = [
                   'first_name',       
                   'last_name',        
                   'gender',           
                   'email',            
                   'date_of_birth',    
                   'contact_no',       
                   'emergeny_contact', 
                   'street_add1',      
                   'street_add2',      
                   'city',             
                   'state',            
                   'postal_code',      
                   'organ',            
        ]
    

src/organdonate/views.py
from django.shortcuts import render

def home(request):
    context = {
        'title': 'Home',
    }
    return render(request, 'home.html', context)

def about(request):
    context = {
        'title': 'About Us',
    }
    return render(request, 'about.html', context)

def contact(request):
    context = {
        'title': 'Contact Us',
    }
    return render(request, 'contact.html', context)

src/register/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import DonorForm
from .models import Donor
from django.shortcuts import get_object_or_404
from reportlab.pdfgen import canvas

def register_donor(request):
    form = DonorForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        context_1 = {
            'title': 'Donor Details',
        }
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'title': 'Register',
        'form': form,
    }
    return render(request, 'register/register_donor.html', context)

def donor_detail(request, id):
    donor = get_object_or_404(Donor, id=id)
    context = {
        'title': 'Donor Details',
        'donor': donor,
    }
    return render(request, 'register/donor_detail.html', context)

def register_success(request):
    context = {
        'title': 'Donor Details',
    }
    return render(request, 'register/register_sucess.html', context)

def download_donor_card(request, id):
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="donor_card.pdf"'

    # Create the PDF object, using the response object as its "file."
    p = canvas.Canvas(response)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 100, id)

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()
    return response 

src/register/templates/register/donor_detail.html
{% extends 'base.html' %}

{% block title %} 
  {{ title }} | {{ block.super }} 
{% endblock title %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{title}}</h1>
<h3>{{ donor.first_name }}</h3>
{{ donor.email }}<br>
{{ donor.date_of_birth }}<br>
<br>

Download your PDF from <a href='donor-card/'>here</a>.
{{donor.id}}
</div>
{% endblock content %}

src/register/templates/register/register_donor.html
{% extends 'base.html' %}

{% block title %} 
  {{ title }} | {{block.super}}
{% endblock title %}


{% block content %}
  <div class='col-sm-6 col-sm-offset-3'>
    <h1> {{title}} </h1>
    
    <form method='POST' action=''>{% csrf_token %}
      {{ form.as_p }}
      <input type='submit' class='btn btn-default' value='Donate'>
    </form>
  </div>
{% endblock content %}

src/templates/.#home.html
saurabh@skynet.2709:1471072618

src/templates/about.html
{% extends 'base.html' %}

{% block title %} 
  {{ title }} | {{block.super}}
{% endblock title %}


{% block content %}
  <div class='col-sm-12 col-sm-offset-0'>
    <h1> {{title}} </h1>
    
  </div>
{% endblock content %}
%}

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %} Donate {% endblock title %}</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <style>{% block style %} {% endblock style %}</style>
</head>

<body>
  <div class="container">

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock content %}
</div>
  <div class="col-md-2"></div>
</div>


  </div>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>

src/templates/contact.html
{% extends 'base.html' %}

{% block title %} 
  {{ title }} | {{block.super}}
{% endblock title %}


{% block content %}
  <div class='col-sm-12 col-sm-offset-0'>
    <h1> {{title}} </h1>
    
  </div>
{% endblock content %}
%}

src/templates/home.html
{% extends 'base.html' %}

{% block title %} 
  {{ title }} | {{block.super}}
{% endblock title %}


{% block content %}
  <div class='col-sm-12 col-sm-offset-0'>
    {% include 'navbar.html' %}
    <h1> {{title}} </h1>
    
  </div>
{% endblock content %}
%}

src/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Give it up!</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'about' %}">About Us<span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'register:create' %}">Register</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>





      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'contact' %}">Contact Us</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>